#!/bin/zsh

set -euo pipefail

OPENPANE_SCRIPT_DIR="${0:A:h}"
OPENPANE_PROJECT_DIR="${OPENPANE_SCRIPT_DIR:h}"
OPENPANE_VERSION="${1:-0.0.1}"
OPENPANE_BUILD_NUMBER="${OPENPANE_BUILD_NUMBER:-1}"
OPENPANE_DIST_DIR="${OPENPANE_PROJECT_DIR}/dist"
OPENPANE_ARCHIVE_NAME="OpenPane-${OPENPANE_VERSION}-macos-arm64.zip"
OPENPANE_ARCHIVE_PATH="${OPENPANE_DIST_DIR}/${OPENPANE_ARCHIVE_NAME}"
OPENPANE_CHECKSUM_PATH="${OPENPANE_DIST_DIR}/SHA256SUMS"

OPENPANE_VERSION="${OPENPANE_VERSION}" \
OPENPANE_BUILD_NUMBER="${OPENPANE_BUILD_NUMBER}" \
    "${OPENPANE_SCRIPT_DIR}/build-app.sh" "${OPENPANE_DIST_DIR}"

/bin/rm -f "${OPENPANE_ARCHIVE_PATH}" "${OPENPANE_CHECKSUM_PATH}"

ditto \
    -c \
    -k \
    --sequesterRsrc \
    --keepParent \
    "${OPENPANE_DIST_DIR}/OpenPane.app" \
    "${OPENPANE_ARCHIVE_PATH}"

(
    cd "${OPENPANE_DIST_DIR}"
    shasum -a 256 "${OPENPANE_ARCHIVE_NAME}" > "SHA256SUMS"
)

echo "${OPENPANE_ARCHIVE_PATH}"
echo "${OPENPANE_CHECKSUM_PATH}"
